version: '3.1'

services:
  web:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=0.0.0.0
      - DB_USER=root
      - DB_PASS=admin
      - DB_NAME=database
      - DB_PORT=3306

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: